[package]
name = "ya6502"
version = "0.1.0"
description = "YA6502 — Yet Another 6502 CPU emulator"
authors = [
    "Bartosz Leper <bl.nero@gmail.com>",
    "technomaniak",
]
edition = "2018"
license = "MIT"

[dependencies]
rand = "0.8.3"
rustasm6502 = "0.1.2"
