name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install the nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: build
        args: --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: test
        args: --verbose
